"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
DEBUG = os.environ.get("DJANGO_DEBUG","False") == "True"

# Comma-separated list from the environment, e.g. "13.233.10.20,my-alb-123.ap-south-1.elb.amazonaws.com"
# ("*" allows any host: OK only for a quick test on AWS, not for real production)
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'django_filters',  # django-filter (1C-4)
    'users',
    'catalog',
    'orders',
]

MIDDLEWARE = [
    'config.health.HealthCheckMiddleware',  # FIRST: answers /health/ before the ALLOWED_HOSTS check
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves admin/DRF CSS+JS inside the container
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ["POSTGRES_DB"],
        'USER': os.environ["POSTGRES_USER"],
        'PASSWORD': os.environ["POSTGRES_PASSWORD"],
        'HOST': os.environ.get("DB_HOST", "localhost"),     # on AWS: the RDS endpoint
        'PORT': os.environ.get("DB_PORT", "5432"),
        # Phase 6 experiments: change these with env vars, no code change needed
        'CONN_MAX_AGE': int(os.environ.get("DB_CONN_MAX_AGE", "0")),   # 0 = new connection per request
        'CONN_HEALTH_CHECKS': True,                         # test a reused connection before using it
        'OPTIONS': {
            # RDS Postgres 15+ forces SSL by default -> "require" on AWS, "prefer" locally
            'sslmode': os.environ.get("DB_SSLMODE", "prefer"),
        },
    }
}

if os.environ.get("DB_POOL", "False") == "True":           # 6-3: Django's built-in pool (psycopg 3)
    DATABASES["default"]["CONN_MAX_AGE"] = 0               # the pool refuses persistent connections
    DATABASES["default"]["OPTIONS"]["pool"] = {
        "min_size": int(os.environ.get("DB_POOL_MIN", "2")),   # kept open and ready
        "max_size": int(os.environ.get("DB_POOL_MAX", "4")),   # PER gunicorn worker process!
        "timeout": int(os.environ.get("DB_POOL_TIMEOUT", "10")),  # seconds to wait for a free connection
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"          # collectstatic copies files here (done in the Dockerfile)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Logs go to stdout -> ECS sends them to CloudWatch
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": os.environ.get("LOG_LEVEL", "INFO")},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

# ---------- Django REST Framework + JWT (1C-1) ----------
from datetime import timedelta  # noqa: E402

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [                               # how DRF finds out "who is calling"
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # reads "Authorization: Bearer <token>"
        "rest_framework.authentication.SessionAuthentication",        # keeps browsable API login working
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # every API needs login unless a view says otherwise
    ],
    "DEFAULT_PAGINATION_CLASS": "config.pagination.StandardPagination",   # every list is paged now
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",   # limits by IP when not logged in
        "rest_framework.throttling.UserRateThrottle",   # limits by user id when logged in
    ],
    "DEFAULT_THROTTLE_RATES": {                         # format: number/second|minute|hour|day
        "anon": "20/minute",
        "user": "60/minute",
        "login": "5/minute",                            # used by LoginView (stops password guessing)
        "restock": "10/hour",                           # used by the restock action (1C-5 exercise)
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),   # short: limits damage if stolen
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),      # long: user stays logged in for a week
}

# Load tests only (Phase 6): the throttle would turn most test requests into 429 errors
if os.environ.get("DISABLE_THROTTLE") == "True":
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []
